<a href="https://colab.research.google.com/github/felippedamasoade/CORRE-O-DE-CATEGORIAS-DE-DESPESAS-EM-PLANILHAS/blob/main/Logistic_Regression_(2).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import random
import spacy
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, accuracy_score
from sklearn.linear_model import LogisticRegression

In [ ]:
!python -m spacy download en_core_web_md

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.8/42.8 MB 15.2 MB/s eta 0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_md')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.


In [ ]:
# Definindo categorias e descrições associadas
categorias_descrições = {
    'Estoque': ['Compra de materiais', 'Aquisição de novos produtos', 'Estoque de segurança'],
    'Marketing': ['Campanha no Google Ads', 'Produção de material publicitário', 'Anúncios em redes sociais'],
    'Utilidades': ['Pagamento da conta de luz', 'Conta de água do escritório', 'Telefone e internet'],
    'Manutenção': ['Manutenção de equipamentos de ar-condicionado', 'Reparo de mobiliário', 'Serviço de limpeza'],
    'Salários': ['Folha de pagamento mensal', 'Adiantamento quinzenal', 'Bônus de final de ano'],
    'Tecnologia': ['Renovação de licença de software', 'Upgrade de equipamentos de TI', 'Suporte técnico'],
    'Serviços Profissionais': ['Honorários de consultoria', 'Serviços legais', 'Contabilidade externa']
}

# Gerar 500 registros
dados = []
for _ in range(500):
    categoria = random.choice(list(categorias_descrições.keys()))
    descrição = random.choice(categorias_descrições[categoria])
    valor = round(random.uniform(100, 5000), 2)
    dados.append([descrição, categoria, valor])

# Criar DataFrame
df_pagamentos = pd.DataFrame(dados, columns=['Descrição', 'Categoria', 'Valor'])

# Visualizando as primeiras linhas dos dados
print(df_pagamentos.head())

# Salvando o DataFrame em um arquivo CSV
df_pagamentos.to_csv('dados_pagamentos.csv', index=False)

                           Descrição               Categoria    Valor
0              Contabilidade externa  Serviços Profissionais   526.74
1                Compra de materiais                 Estoque  4890.00
2  Produção de material publicitário               Marketing  1195.05
3               Estoque de segurança                 Estoque  3713.53
4          Pagamento da conta de luz              Utilidades   275.68


In [ ]:
nlp = spacy.load('en_core_web_md')

In [ ]:
def get_vectors(text):
    return nlp(text).vector

In [ ]:
df_pagamentos['Vectors'] = df_pagamentos['Descrição'].apply(get_vectors)

In [ ]:
X = np.array(list(df_pagamentos['Vectors']))
y = df_pagamentos['Categoria']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2, random_state=42)

In [ ]:
model2 = LogisticRegression(max_iter=1000) # Aumentar max_iter se a convergencia nao for alcançada
model2.fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(max_iter=1000)

In [ ]:
y_pred2 = model2.predict(X_test)

In [ ]:
print(classification_report(y_test, y_pred2))
print('Acuracia do modelo', accuracy_score(y_test,y_pred2))

                        precision    recall  f1-score   support

               Estoque       1.00      1.00      1.00         8
            Manutenção       1.00      0.65      0.79        20
             Marketing       1.00      1.00      1.00        13
              Salários       1.00      1.00      1.00        22
Serviços Profissionais       0.68      1.00      0.81        15
            Tecnologia       1.00      1.00      1.00        10
            Utilidades       1.00      1.00      1.00        12

              accuracy                           0.93       100
             macro avg       0.95      0.95      0.94       100
          weighted avg       0.95      0.93      0.93       100

Acuracia do modelo 0.93


Matriz de Confusão

In [ ]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, recall_score, f1_score, roc_auc_score

# Supondo que X e y sejam seus dados e rótulos
# Divisão dos dados
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Treinamento do modelo
rf_clf = RandomForestClassifier(n_estimators=100, random_state=42)
rf_clf.fit(X_train, y_train)

# Previsões
y_pred_rf = rf_clf.predict(X_test)

# Matriz de Confusão
cm_rf = confusion_matrix(y_test, y_pred_rf)
print("Matriz de Confusão - Random Forest:")
print(cm_rf)

# Métricas
accuracy_rf = accuracy_score(y_test, y_pred_rf)
recall_rf = recall_score(y_test, y_pred_rf, average='weighted')
f1_rf = f1_score(y_test, y_pred_rf, average='weighted')

# AUC-ROC para múltiplas classes
auc_rf = roc_auc_score(y_test, rf_clf.predict_proba(X_test), multi_class='ovr')

print(f"Precisão (Accuracy): {accuracy_rf}")
print(f"Recall: {recall_rf}")
print(f"F1-score: {f1_rf}")
print(f"AUC-ROC: {auc_rf}")


Matriz de Confusão - Random Forest:
[[ 8  0  0  0  0  0  0]
 [ 0 13  0  0  7  0  0]
 [ 0  0 13  0  0  0  0]
 [ 0  0  0 22  0  0  0]
 [ 0  0  0  0 15  0  0]
 [ 0  0  0  0  0 10  0]
 [ 0  0  0  0  0  0 12]]
Precisão (Accuracy): 0.93
Recall: 0.93
F1-score: 0.9291973791973792
AUC-ROC: 0.9950674019607842
